version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user

hooks:
  BeforeInstall:
    - location: scripts/appstop.sh    
      runas: root
  ApplicationStart:
    - location: scripts/appstart.sh
      runas: root
  