version: 0.2

phases:
  install:
    runtime-versions:
      docker: 18
      
  build:
    commands:
      - aws s3 cp StaticWeb/index.html s3://semox/ --acl public-read
      - aws s3 cp StaticWeb/room.html s3://semox/ --acl public-read
      - aws ecr get-login-password --region ap-northeast-2 | docker login --username AWS --password-stdin 593634833876.dkr.ecr.ap-northeast-2.amazonaws.com
      - docker build -t semox:latest .
      - docker tag semox:latest 593634833876.dkr.ecr.ap-northeast-2.amazonaws.com/semox:latest
      - docker push 593634833876.dkr.ecr.ap-northeast-2.amazonaws.com/semox:latest
  
artifacts:
  files:
    - appspec.yml
    - code/socket.js