version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 12
      docker: 18
      
  build:
    commands:
      - aws s3 cp StaticWeb/index.html s3://semox/ --acl public-read
      - aws s3 cp StaticWeb/room.html s3://semox/ --acl public-read
      - aws ecr get-login-password --region ap-northeast-2 | docker login --username AWS --password-stdin 593634833876.dkr.ecr.ap-northeast-2.amazonaws.com
      - DATE=$(date +%y-%m-%d)
      - docker pull public.ecr.aws/docker/library/node:slim
      - docker build -t semox_repo:$DATE .
      - docker tag semox_repo:$DATE 593634833876.dkr.ecr.ap-northeast-2.amazonaws.com/semox_repo:$DATE
      - docker images
      - docker push 593634833876.dkr.ecr.ap-northeast-2.amazonaws.com/semox_repo:$DATE
  
artifacts:
  files:
    - appspec.yml
    - code/socket.js